# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Zjg5NThkMjQwMDVmZjY1ODJjNTI2Y2NhOWZlOTMxMzNlNTZhMjY2ZjU2N2U1YzhlYzZmN2Q3MzYxMzdiYzExNGJjMDVkYTE4ODRiOGRiYWY3MjllZWEwMTgzZjRmNWQzMjMwMjNiM2U2YTJkZmY5ZmM1NjU1NTRmMDRjYmJkYTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
